# 把 exe 与 dll 统一输出到工程根目录下的 Release。
set(BIN_OUTPUT_DIR "${CMAKE_SOURCE_DIR}/Release")

# 把静态库统一输出到工程根目录下的 lib。
set(LIB_OUTPUT_DIR "${CMAKE_SOURCE_DIR}/lib")

# 先设置所有配置共用的默认输出目录。
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${BIN_OUTPUT_DIR}")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${BIN_OUTPUT_DIR}")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${LIB_OUTPUT_DIR}")

# 再显式覆盖 Release，避免 VS 多配置生成器额外再拼一个 /Release 子目录。
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE "${BIN_OUTPUT_DIR}")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE "${BIN_OUTPUT_DIR}")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${LIB_OUTPUT_DIR}")
